# Generated by Django 5.2.9 on 2025-12-20 01:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_itemorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.fooditem'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='menu.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorder',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
