# Generated by Django 5.2.9 on 2025-12-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_itemorder_item_id_itemorder_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.fooditem'),
        ),
    ]
