# Generated by Django 5.2.9 on 2025-12-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_itemorder_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pickup_datetime']},
        ),
    ]
