# Generated by Django 5.2.9 on 2026-01-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
