# Generated by Django 5.2.9 on 2026-01-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_itemorder_line_total_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
