# Generated by Django 5.2.9 on 2026-01-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_order_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='order_id',
            new_name='order',
        ),
    ]
