# Generated by Django 5.2.9 on 2026-01-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_order_id_itemorder_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='item_id',
            new_name='item',
        ),
    ]
