# Generated by Django 5.2.9 on 2026-01-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_active_remove_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of the item at the time of ordering (locked)', max_digits=6),
        ),
    ]
